config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'todos#index'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
    @todos = TodoList.all
    end
    def show
     @todo = TodoList.find(params[:id])
    end
    def new
    @todo = TodoList.new
    end
    def create
    @todo = TodoList.create todo_params
    redirect_to todo_path(@todo)
    end
    def edit
      @todo = TodoList.find(params[:id])
    end
    def update
        p "sddfsf"
        @todo = TodoList.find(params[:id])
        @todo.update todo_params
        redirect_to todo_path(@todo)
    end
    def destroy
        TodoList.find(params[:id]).destroy
        redirect_to root_path
    end
    end
private
    def todo_params
      params.require(:todo).permit(:title, :description)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Your Selected Todo</h1>
<%= form_tag ('/todos') do%>
  <%= label_tag(:title, "Title:") %>
  <%= text_field "todo", "title" %></br>
  <%= label_tag(:description, "Description") %>
  <%= text_area "todo", "description" %></br>
  <%= submit_tag "Update" %>
<% end %>

app/views/todos/index.html.erb
<h1> TODO APP! </h1>
<%= link_to "New Todo Item", new_todo_path %>
<% @todos.each do |todo| %>
    <li>
      <%= link_to todo.title, todo_path(todo.id) %>
      <%= link_to "edit", edit_todo_path(todo[:id]) %>
      <%= link_to "Delete", {action: :destroy, id: todo.id}, method: :delete, data: { confirm: "You sure?" }%>
    </li>
<% end %>

app/views/todos/new.html.erb
<h1>Create a New Todo</h1>
<%= form_tag :action => 'create' do %>

  <%= label_tag(:title, "Title:") %>
  <%= text_field "todo","title" ,  required: true %></br>
  <%= label_tag(:description, "Description") %>
  <%= text_area "todo", "description",  required: true %></br>
  <%= submit_tag "Create" %>
<% end %>

app/views/todos/show.html.erb
<h1>Your New ToDo</h1>
<p>Title: <%= @todo['title']%></p>
<p>Description: <%= @todo['description']%></p>

<%= link_to "Back To Todo List",todos_path%>